const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const listeners={};global.window={addEventListener:(n,f)=>{(listeners[n]||(listeners[n]=[])).push(f)},dispatchEvent:()=>{},location:{pathname:'/'} };
global.document={documentElement:{dataset:{base:'./'}},querySelectorAll:()=>[],querySelector:()=>null,body:{classList:{add:()=>{}}},head:{appendChild:()=>{}},createElement:()=>({setAttribute:()=>{},classList:{add:()=>{}},appendChild:()=>{}})};global.location={pathname:'/',href:'http://localhost/'};global.Event=function(n){this.type=n};global.navigator={};const mem={};global.localStorage={getItem:k=>mem[k]||null,setItem:(k,v)=>mem[k]=v,removeItem:k=>delete mem[k]};
let src=fs.readFileSync(path.join(root,'assets/js/app.js'),'utf8')+'\n;globalThis.BM_TEST=BM;';vm.runInThisContext(src,{filename:'app.js'});const B=global.BM_TEST;
function wire(){B.json=async function(rel){if(this.cache[rel])return this.cache[rel];return this.cache[rel]=JSON.parse(fs.readFileSync(path.join(root,rel),'utf8'))};B.jsonOptional=async function(rel,f){try{return await this.json(rel)}catch{return f}}}
const synthetic=[
{id:'bdns-test-mun',title:'Digitalización municipios',review_status:'pending',status:'pending_review',application_status:'open_detected',topics:['digitalizacion','administracion'],beneficiary_types:['municipality','local_entity'],beneficiary_targets:['municipality','local_entity'],territories:['España'],population_rules:[{max:5000,basis:'municipality'}],deadline:'2026-09-30',bases_url:'x',extraction_confidence:'high',detection_score:25,organization:'Estado',summary:'test'},
{id:'bdns-test-private',title:'Empresas',review_status:'pending',status:'pending_review',application_status:'open_detected',topics:['digitalizacion'],beneficiary_types:['company'],beneficiary_targets:['company'],territories:['España'],deadline:'2026-09-30',extraction_confidence:'high',detection_score:20,organization:'Estado',summary:'test'},
{id:'bdns-test-eatim',title:'EATIM',review_status:'pending',status:'pending_review',application_status:'open_detected',topics:['servicios','despoblacion'],beneficiary_types:['eatim','local_entity'],beneficiary_targets:['eatim','local_entity'],territories:['Castilla-La Mancha'],population_rules:[{max:500,basis:'eatim'}],deadline:'2026-09-30',bases_url:'x',extraction_confidence:'high',detection_score:20,organization:'CLM',summary:'test'},
{id:'bdns-test-closed',title:'Cerrada',review_status:'pending',status:'pending_review',application_status:'closed_detected',topics:['servicios'],beneficiary_types:['municipality'],beneficiary_targets:['municipality'],territories:['España'],deadline:'2026-08-01',extraction_confidence:'high',detection_score:20,organization:'Estado',summary:'test'}];
async function seedOpps(){const curated=await B.json('data/catalog/oportunidades.json');B.cache.__opps=[...curated,...synthetic]}
(async()=>{wire();const mun={id:'test-mun',name:'Villa Test',entity_type:'municipality',province:'Ciudad Real',autonomous_region:'Castilla-La Mancha',population:800};const eatim={id:'test-eatim',name:'Aldea Test',entity_type:'eatim',province:'Ciudad Real',autonomous_region:'Castilla-La Mancha',population:120,municipal_population:800,parent_municipality:'Villa Test'};B.resolveAdministrativeMunicipality=async p=>p.entity_type==='municipality'?p:{...mun,name:'Villa Test'};await seedOpps();
 const ctx=await B.smartContext(mun);if(ctx.capacity.id!=='very_small')throw Error('capacity band');const obls=await B.smartObligationLayers(mun),channel=obls.curated.find(x=>x.o.id==='canal-interno');if(!channel||channel.fit.decision!=='shared_compliance')throw Error('canal interno shared route');const opps=await B.smartOpportunityLayers(mun);if(!opps.likely.some(x=>x.o.id==='bdns-test-mun'))throw Error('municipal opportunity not likely');if(!opps.excluded.some(x=>x.o.id==='bdns-test-private'))throw Error('private opportunity not excluded');if(!opps.excluded.some(x=>x.o.id==='bdns-test-closed'))throw Error('closed not excluded');
 B.cache={};wire();B.resolveAdministrativeMunicipality=async p=>p.entity_type==='municipality'?p:{...mun,name:'Villa Test'};await seedOpps();const ectx=await B.smartContext(eatim);if(ectx.capacity.id!=='micro'||ectx.legalPopulation!==800||ectx.localPopulation!==120)throw Error('dual EATIM population context');const eo=await B.smartOpportunityLayers(eatim),e=eo.likely.find(x=>x.o.id==='bdns-test-eatim')||eo.possible.find(x=>x.o.id==='bdns-test-eatim');if(!e||e.fit.match.route!=='eatim_direct')throw Error('EATIM direct route');
 const projects=await B.smartProjectRecommendations(mun,12);if(projects.length!==12)throw Error('project count');const topCats={};for(const x of projects.slice(0,6))topCats[x.p.category]=(topCats[x.p.category]||0)+1;if(Math.max(...Object.values(topCats))>2)throw Error('diversity');console.log('OK test_decision_engine_v140: capacity, shared compliance, BDNS gates, dual EATIM scale, EATIM route, diversity.');
})().catch(e=>{console.error(e);process.exit(1)});
